apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  type: ClusterIP
  selector:
    app: notifications-service
  ports:
    - name: http
      port: 3007
      targetPort: 3007
