apiVersion: v1
kind: Secret
metadata:
  name: squirrel-app-secrets
type: Opaque
data:
  SQUIRREL_INTERNAL_KEY: Y2hhbmdlLW1l
  JWT_PUBLIC_KEY: UkVQTEFDRV9XSVRIX0pXVF9QVUJMSUNfS0VZ
  JWT_PRIVATE_KEY: UkVQTEFDRV9XSVRIX0pXVF9QUklWQVRFX0tFWQ==
  JWT_SECRET: UkVQTEFDRV9XSVRIX0pXVF9TRUNSRVQ=
  REFRESH_SECRET: UkVQTEFDRV9XSVRIX1JFRlJFU0hfU0VDUkVU
  AUTH_POSTGRES_URL: cG9zdGdyZXNxbDovL3NxdWlycmVsOnNlY3JldEBwb3N0Z3Jlczo1NDMyL3NxdWlycmVsX2F1dGg=
  USER_POSTGRES_URL: cG9zdGdyZXNxbDovL3NxdWlycmVsOnNlY3JldEBwb3N0Z3Jlczo1NDMyL3NxdWlycmVsX3VzZXJz
  WORKSPACE_POSTGRES_URL: cG9zdGdyZXNxbDovL3NxdWlycmVsOnNlY3JldEBwb3N0Z3Jlczo1NDMyL3NxdWlycmVsX3dvcmtzcGFjZXM=
  BILLING_POSTGRES_URL: cG9zdGdyZXNxbDovL3NxdWlycmVsOnNlY3JldEBwb3N0Z3Jlczo1NDMyL3NxdWlycmVsX2JpbGxpbmc=
  LOGS_POSTGRES_URL: cG9zdGdyZXNxbDovL3NxdWlycmVsOnNlY3JldEBwb3N0Z3Jlczo1NDMyL3NxdWlycmVsX2xvZ3M=
  OPENAI_API_KEY: T1BFTkFJX0FQSV9LRVlfUExBQ0VIT0xERVI=
  FCM_SERVICE_ACCOUNT_KEY: RkNNX1NFUlZJQ0VfQUNDT1VOVF9LRVlfUExBQ0VIT0xERVI=
  SMTP_URL: c210cDovL3VzZXI6cGFzc0BtYWlsOjU4Nw==
